
- block:
  - name: License File
    shell: "echo 'license_key: {{license}}' | sudo tee -a /etc/newrelic-infra.yml"
  - name: NewRelic GPG Key
    shell: curl -s https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg | sudo apt-key add -
  - name: NewRelic Repo
    shell: printf "deb https://download.newrelic.com/infrastructure_agent/linux/apt focal main" | sudo tee -a /etc/apt/sources.list.d/newrelic-infra.list
  - name: Update
    shell: sudo apt-get update
  - name: Dependency
    shell: sudo apt-get install libcap2-bin
  - name: Install
    shell: "sudo apt-get install newrelic-infra"
    environment:
      NRIA_MODE: "PRIVILEGED"
    become: true
  become: true
  when: ansible_system == "Linux"

- block:
  - name: Windows Install
    ansible.windows.win_package:
      path: https://download.newrelic.com/infrastructure_agent/windows/newrelic-infra.msi
  
  - name: License file
    win_lineinfile:
      path: 'C:\Program Files\New Relic\newrelic-infra\newrelic-infra.yml'
      line:  'license_key: {{license}}'
      insertbefore: BOF
  
  - name: License file
    win_lineinfile:
      path: 'C:\Program Files\New Relic\newrelic-infra\newrelic-infra.yml'
      line:  'license_key: <ENTER YOUR NEW RELIC KEY HERE>'
      state: absent

  - name: Windows Start
    ansible.windows.win_shell: net start newrelic-infra
  when: ansible_os_family == "Windows"