
- block:
  - name: Install
    shell: "curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash && sudo  NEW_RELIC_API_KEY=NRAK-9VLYTCZDYAE9B8KBU48BQ929JKX NEW_RELIC_ACCOUNT_ID=3425996 /usr/local/bin/newrelic install"
    become: true
  become: true
  when: ansible_system == "Linux"

- block:
  - name: Windows Install
    ansible.windows.win_package:
      path: https://download.newrelic.com/infrastructure_agent/windows/newrelic-infra.msi
  
  - name: License file
    win_lineinfile:
      path: 'C:\Program Files\New Relic\newrelic-infra\newrelic-infra.yml'
      line:  'license_key: {{license}}'
      insertbefore: BOF
  
  - name: License file
    win_lineinfile:
      path: 'C:\Program Files\New Relic\newrelic-infra\newrelic-infra.yml'
      line:  'license_key: <ENTER YOUR NEW RELIC KEY HERE>'
      state: absent

  #- name: Windows Start
  #  ansible.windows.win_shell: net start newrelic-infra
  when: ansible_os_family == "Windows"