- name: update apt
  apt:
    update_cache: True

- name: Install snap
  apt:
    name: snapd
    state: present

- name: Enable snap
  shell:
    cmd: systemctl enable --now snapd apparmor

- name: Make sure snapd service unit is running
  ansible.builtin.systemd:
    state: started
    name: snapd
  
- name: Make sure apparmor service unit is running
  ansible.builtin.systemd:
    state: started
    name: apparmor

- name: Install curl
  apt:
    name: curl
    state: present

- name: Install lsd
  snap:
    name: lsd

- name: Install neofetch
  apt:
    name: neofetch


- name: Install code
  snap:
    name: code
    classic: yes

- name: Install git-kraken
  snap:
    name: gitkraken
    classic: yes

- name: Install joplin
  snap:
    name: joplin
    classic: yes

- name: Install powershell
  snap:
    name: powershell
    classic: yes


- name: Install McFly
  shell: curl -LSfs https://raw.githubusercontent.com/cantino/mcfly/master/ci/install.sh | sh -s -- --git cantino/mcfly --force

- name: Add McFly to .bashrc
  lineinfile:
    dest: /home/dan/.bashrc
    line: 'eval "$(mcfly init bash)"'
    owner: dan
    state: present
    insertafter: EOF
    create: True

- name: Install ansible
  apt:
    name: ansible




