- name: install apt-transport-https
  apt:
    name: apt-transport-https

- name: ensure curl present
  apt:
    name: curl
    state: present


- name: Add openvpn gpg key
  shell: curl -fsSL https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/openvpn-repo-pkg-keyring.gpg

- name: add source
  shell: curl -fsSL https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-jammy.list >/etc/apt/sources.list.d/openvpn3.list

- name: update apt
  apt:
    update_cache: True

- name: install openvpn
  apt: 
    name: openvpn3

- name: copy profile
  copy:
    src: profile.ovpn
    dest: /home/dan/profile.ovpn

- name: import profile
  shell: openvpn3 config-import --config /home/dan/profile.ovpn
  become_user: dan

- name: rename profile
  shell: openvpn3 config-manage --config /home/dan/profile.ovpn --rename aka-q9
  become_user: dan


