---
- name: all=ping
  hosts: all
  
  tasks:
    - name: Linux Ping
      ansible.builtin.ping:
      when: ansible_system == "Linux"
    - name: Windows Ping
      ansible.builtin.win_ping:
      when: ansible_os_family == "Windows"