---
- name: windows-hardening-audit
  hosts: windows
  
  tasks:
  - name: Display Windows Version
    ansible.builtin.debug: 
      var: ansible_facts['distribution_version']
  
  - name: Ensure temp exists
    ansible.windows.win_file:
      path: C:\temp
      state: directory
  
  - name: Copy hardening repo
    ansible.windows.win_copy:
      src: /mnt/d/repos/windows_hardening
      dest: C:\temp

  # 2012 R2 - 6.3.9600.0
  - block:
    - name: Run 2012R2 Audit
      ansible.windows.win_shell: c:\temp\windows_hardening\audit2012r2.ps1
      register: host_out
    - name: Create report.log  
      ansible.windows.win_copy:
        content: "{{host_out.stdout}}"
        dest: C:\temp\windows_hardening\report.log
    when: ansible_facts['distribution_version'] == "6.3.9600.0"

  # 2016 - 10.0.14393.0
  - block:
    - name: Run 2016 Audit
      ansible.windows.win_shell: c:\temp\windows_hardening\audit2016.ps1
      register: host_out
    - name: Create report.log  
      ansible.windows.win_copy:
        content: "{{host_out.stdout}}"
        dest: C:\temp\windows_hardening\report.log
    when: ansible_facts['distribution_version'] == "10.0.14393.0"

  # 2019 - 10.0.17763.0
  - block:
    - name: Run 2019 Audit
      ansible.windows.win_shell: c:\temp\windows_hardening\audit2019.ps1
      register: host_out
    - name: Create report.log  
      ansible.windows.win_copy:
        content: "{{host_out.stdout}}"
        dest: C:\temp\windows_hardening\report.log
    when: ansible_facts['distribution_version'] == "10.0.17763.0"

  
  - name: Fetch report file
    fetch: src=C:/temp/windows_hardening/report.log dest=/reports/hardening-audit-{{inventory_hostname}}-{{ ansible_date_time.iso8601 }}.log flat=yes
  
  - name: Clean up
    ansible.windows.win_file:
      path: C:\temp\windows_hardening
      state: absent
