
- block:
  - name: Linux Install
    ansible.builtin.shell: "curl --tlsv1.2 --silent --show-error --header 'x-connect-key: {{connect_key}}' https://kickstart.jumpcloud.com/Kickstart | sudo bash"
    become: true
  when: ansible_system == "Linux"

- block:
  - name: Windows Install
    ansible.windows.win_powershell:
      script: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; 
        cd $env:temp | Invoke-Expression; 
        Invoke-RestMethod -Method Get -URI https://raw.githubusercontent.com/TheJumpCloud/support/master/scripts/windows/InstallWindowsAgent.ps1 -OutFile InstallWindowsAgent.ps1 | Invoke-Expression; 
        ./InstallWindowsAgent.ps1 -JumpCloudConnectKey "{{connect_key}}"
  when: ansible_os_family == "Windows"



